### ISSUE TITLE
Hardware problem: constant resets

### ISSUE THREAD

**Issue by alex8065** [joeycastillo/Sensor-Watch#251]
Anyone observe this? Watch loses time and restarts. Loose battery perhaps?

EDIT: I can consistently reproduce this by pressing on the battery casing. The red LED will blink once, and the watch will reset and start again after a few seconds.

**Comment by ChristophDerndorfer** [comment]
FWIW: I haven't seen this issue in the past 6 months with about 2~3 disassemblies done during that time.

**Comment by CH23-** [comment]
I have had this behaviour, it's most likely that one of the tabs on the battery shield is not properly connected, and so there is a power interruption

**Comment by h6y3** [comment]
I saw this issue during assembly and it was related to the battery shield being properly connected; though to be fair I don't know what that means because in my case I had clear signs it was not connected but the tabs and everything else seemed fine.  It simply restarts or loses power upon pressing the casing.  I finally got it working after about 30 minutes of fiddling.  It was easily the hardest part of the build for me - the soldering, editing and even building custom firmware turned out to be trivial in comparison but getting the battery shield on was hard.

**Comment by alex8065** [comment]
Resets kept happening on and off. Finally got around to installing another board (had a few backups), and this one doesn't have the same issue. Casing and battery are the same. Pressing no longer causes resets with the new board.

Suspecting a hardware/assembly issue, maybe @joeycastillo /someone who has a better view of the board design could chime in with what might be getting shorted here.

To be clear, it's not a power loss issue (where the display markings fade), the red LED blinks a few times and then the watch restarts at T+0.

**Comment by 814d3** [comment]
Sadly, I experience a similar reaction. Not so easy to reproduce, but pressure on the upper left half of the case/screen area sometimes activates the red LED and the display briefly disappears. The time is then still correct, but running timers, for example, are reset. (Green Board with Sensor Board)
I'll try to adjust the battery tabs on the next disassembly - hope that helps...

**Comment by chris-v8** [comment]
I too experience this issue. Good hour of bending the battery shielding tabs and the (-) pole tab on the PCB gave no effect. I believe that either there is a design error in the traces of PCB, or which seems more reasonable to me, a capacitor is being shorted. What could confirm my theory, is that if you would "reset" the watch a few times, it would start showing LAP indicator indicating the low battery, which clearly was not the case. Upon checking the voltage_face, It was reading around 1.9V, and began to rise to it's nominal voltage in less than a minute. That gives me the idea that some capacitor is being shorted, watch microcontroller prevents such load, watch restarts, and the capacitor recharges. Sadly I don't have the time resources to investigate further, so I the issue has to stay open.

**Comment by chris-v8** [comment]
I think I have managed to find a solution.
I have bought new casio watch that i've dissasembled. I have taken a closer look at the rubber strip that connects PCB with the LCD, and to my surprise new casio had the strip over .2-3mm (maybe little less) sticking out more than the other case I had problems with. The case that I've used previously is from around 2015. I only swapped the strip onm this old case. I've been playing for good 10 minutes pressing on different places, even dropping the watch (which also caused restarts) and the issue seems to be gone :)
![IMG20240423215418](https://github.com/joeycastillo/Sensor-Watch/assets/166921654/af348046-72fa-49ee-9b4d-3218aaf07e78)
On the picture they look identical, but after assembly it's actually sticking out just a tiny bit more.

**Comment by city41** [comment]
I had this problem on a fresh install into a new f91w.l just now.

Not sure what I did, but taking everything apart then back together again fixed it.

And to be clear: pushing the light button would cause the watch face to go blank, then a second or so later start up again, much like a "reboot". When it did this the led would shine red. The other two buttons worked fine.

**Comment by chris-v8** [comment]
Sensor watch PCB is just a bit thicker than regular F91w. Speaking from experience it's very easy for the metal tabs that hook to the white case to not hook fully, and so the one of two probes on the metal case doesn't make contact, which is what causes behavior you've described.

**Comment by 814d3** [comment]
Maybe it is of interest, I've been using a W-59 housing for around 5 weeks and had no resets so far. The housing is slightly bigger, what maybe helps to reduce pressure in certain situations.

**Comment by blinken** [comment]
I had a similar issue, and I was able to solve my problem. It might be different for others.

The watch would power off as soon as I pressed in the 4th battery tab (in any order). With all tabs pressed in, if I pushed tweezers between the battery and the PCB, it would power up. A multimeter showed that the battery was being shorted out when all clips were in.

By gently flexing the battery cover, I was able to get the watch to start up with all clips in, however pressing on the rear of the battery (and in particular the lower-left side) would cause it to reboot. It seemed that when the battery was pressed hard against the circuit board, it would short out.

Looking at the PCB with a loupe, there were two potential issues:
 - A tiny scratch that was exposing copper, either from manufacturing or my own mishandling.

![image](https://github.com/user-attachments/assets/2900ae50-4ad6-445e-96e0-15a8b0c4eb7f)

I placed a piece of kapton tape on the scratch and this improved but did not resolve the issue.

![image](https://github.com/user-attachments/assets/43beb101-447d-4f48-981a-74f4f7d2ef41)

- Looking closer, the solder mask was damaged around this test point. There was a corresponding rough piece on the backing shield that was cutting in to the PCB.

![image](https://github.com/user-attachments/assets/b6201397-7e6d-4a9b-8939-2e0061a26eaf)
![image](https://github.com/user-attachments/assets/7b9be3f4-57c5-4731-8238-cfe3bd429182)

I placed more kapton tape over the mark and filed back the rough spot on the battery cover.

![image](https://github.com/user-attachments/assets/13ebd5f9-93e2-43d1-bf4d-af542a6741b7)
![image](https://github.com/user-attachments/assets/ffd51944-9b5c-46dd-9e36-5aecdd1d5a3d)

This has completely resolved the issue for me.

**Comment by 814d3** [comment]
Apparently, the sporadic resets are still happening with my SW, and I just hadn't noticed them before. I've only noticed it now because I've had a daily alarm set for about three weeks, and it's now "disappeared" for the second time, meaning no more alarms are displayed/set (firmware default). It's a bit annoying.

**Comment by crostgaard** [comment]
Thanks for posting the solution. I had the exact same problem where a sharp edge on the battery case scraped through the coating on the PCB.
I had the issue on both bottom sides of the casing, so I added two pieces of kapton tape.
This completely solved the reset problem.  
<img width="535" height="473" alt="Image" src="https://github.com/user-attachments/assets/38108e4d-0b44-457f-bedd-ebe5b7a2be82" /> 

<img width="839" height="529" alt="Image" src="https://github.com/user-attachments/assets/14207a33-b0eb-43db-acc4-e0056365e20b" />
